package com.example.TimeCommunityVaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AddCourseDesign extends VerticalLayout {
	protected TextField course;
	protected TextField courseCode;
	protected TextField introduction;
	protected DateField time;
	protected DateField endTime;
	protected ComboBox startTimeOfDay;
	protected ComboBox durationHours;
	protected ComboBox weekDay;
	protected TextField location;
	protected ComboBox startTimeOfDay2;
	protected ComboBox durationHours2;
	protected ComboBox weekDay2;
	protected TextField location2;
	protected Button completebutton;
	protected Button cancelbutton;

	public AddCourseDesign() {
		Design.read(this);
	}
}
