package com.example.TimeCommunityVaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CommunityViewDesign extends AbsoluteLayout implements Button.ClickListener {
	protected Button addbutton;

	public CommunityViewDesign() {
		Design.read(this);
		addbutton.addClickListener(this);
		
	}

	@Override
	public void buttonClick(ClickEvent event) {
		// TODO Auto-generated method stub
		//Notification.show("This is Test");
		Window subwindow =new Window("Add a Course");
		subwindow.setWidth("400px");
		subwindow.setHeight("450px");
		
		subwindow.setModal(true);
		subwindow.center();
		/*VerticalLayout layout = (VerticalLayout) subwindow.getContent();
        layout.setMargin(true);
        layout.setSpacing(true);
        // make it fill the whole window
        layout.setSizeFull();*/
		//UI.addWindow(subwindow);
		AddCourseDesign addcourseview=new AddCourseDesign();
		subwindow.setContent(addcourseview);
		UI.getCurrent().addWindow(subwindow);
	
		
	}
}
