package com.example.TimeCommunityVaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.data.Item;
import com.vaadin.data.util.PropertysetItem;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Table;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CommunityViewDesign extends AbsoluteLayout implements Button.ClickListener {
	protected Button addbutton;
	protected VerticalLayout courselistlayout;
	 AddCourseDesign addcourse=new AddCourseDesign();
	 Table table = new Table("CourseLists:");
	 String coursenamestr;
		String coursecodestr;
		String timestr;
		String locationstr;
		String introductionstr;
		PropertysetItem itemsample;
		int j=1;
	 
	@SuppressWarnings("unchecked")
	public CommunityViewDesign() {
		Design.read(this);
		

    	// Define two columns for the built-in container
    	table.addContainerProperty("Course", String.class, null);
    	table.addContainerProperty("CourseCode",  String.class, null);
    	table.addContainerProperty("Time",  String.class, null);
    	table.addContainerProperty("Location",  String.class, null);
    	table.addContainerProperty("Introduction",  String.class, null);
        
     
    	//*/ Add a row the hard way
    	Object newItemId = table.addItem();
    	Item row1 = table.getItem(newItemId);
    	row1.getItemProperty("Course").setValue("Modern Web Apllication");
    	row1.getItemProperty("CourseCode").setValue("465908");
    	row1.getItemProperty("Time").setValue("465908");
    	row1.getItemProperty("Location").setValue("Agro 110/A, Turku");
    	row1.getItemProperty("Introduction").setValue("Web Application Development based on Vaadin framwork.");
    	
    	
		
		
		courselistlayout.addComponent(table);
    	table.setPageLength(5);
		addbutton.addClickListener(this);
	}

	@Override
	public void buttonClick(ClickEvent event) {
		// TODO Auto-generated method stub
		//Notification.show("This is Test");
		
		new AddSubWindow(); 
	
		
	}

	public void initTable(PropertysetItem item, int i){

		      j=i;
    		 coursenamestr=item.getItemProperty("coursenameid").getValue().toString();
    	     coursecodestr=item.getItemProperty("coursecodeid").getValue().toString();
    		 timestr=item.getItemProperty("coursetimeid").getValue().toString();
    	     locationstr=item.getItemProperty("courselocationid").getValue().toString();
    		 introductionstr=item.getItemProperty("courseintroductionid").getValue().toString();

    		 Notification.show("bytbyt"+coursenamestr+""+coursecodestr+""+timestr+""+locationstr+""+introductionstr);

    			if(j>1){
    				 Notification.show("say goodbay"+String.valueOf(j));
    				 table.addItem(new Object[]{coursenamestr,coursecodestr,timestr,locationstr,introductionstr},j);
    		         
    		         //Notification.show("huhuib"+table.getItem(j).getItemProperty("Course").getValue().toString());
    			}
			 
            //table.addItem(new Object[] {coursenamestr,coursecodestr,timestr,locationstr,introductionstr});
           
	}
	

	public void Coursetable(){

		
		
		if(j>1){
			 Notification.show("say goodbay"+String.valueOf(j));
			 table.addItem(new Object[]{coursenamestr,coursecodestr,timestr,locationstr,introductionstr},j);
	         
	         //Notification.show("huhuib"+table.getItem(j).getItemProperty("Course").getValue().toString());
			 
	     	
	        courselistlayout.addComponent(table);
	        addComponent(courselistlayout);
	     	table.setPageLength(7);
	       
		}
			
	}
}
