package com.example.TimeCommunityVaadin;

import com.example.TimeCommunityVaadin.scheduleView.Course;
import com.example.TimeCommunityVaadin.scheduleView.DatabaseProxy;
import com.example.TimeCommunityVaadin.scheduleView.ScheduleComponent;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Label;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.Notification;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TimeCommunityDesign extends AbsoluteLayout implements Property.ValueChangeListener {
	protected HorizontalLayout hlayout;
	protected Label titlelabel;
	protected HorizontalSplitPanel hsplit;
	protected ListSelect listview;
	protected AbsoluteLayout communitylayout;

	public TimeCommunityDesign() {
		Design.read(this);
		listview.addValueChangeListener(this);
		listview.select("Community");
	}

	@Override
	public void valueChange(ValueChangeEvent event) {
		// TODO Auto-generated method stub
		String listviewstr=event.getProperty().getValue().toString();
		
		switch(listviewstr){
		
		case"Community": 
			             CommunityViewDesign communityview=new CommunityViewDesign();
			             communitylayout.removeAllComponents();
		                 communitylayout.addComponent(communityview);
		                 hsplit.setSecondComponent(communitylayout);
			break;
		case"My Schedule":
			             //AddCourseDesign addview=new AddCourseDesign();
			             communitylayout.removeAllComponents();
			             //communitylayout.addComponent(addview);
			             //hsplit.setSecondComponent(communitylayout);
			             hsplit.setSecondComponent(initializeScheduleComponent());
			
			             
			             //Notification.show(listviewstr+"Hello !!!!");
			break;
		case"My Event":
			             communitylayout.removeAllComponents();
			             Notification.show(listviewstr+"halp hahaha!!!!");
			break;
		default:
			break;
		}
	}
	
	private ScheduleComponent initializeScheduleComponent(){
		//Courses have to be retrieved from a database class, which is connected to database
		Course[] courses = new DatabaseProxy().getCourses();
		ScheduleComponent sc = new ScheduleComponent(courses);
		return sc;
	}
}
